- name: Download wordpress into /srv/wordpress using wp[-cli] command as the wordpress user
  command: "wp core download --path={{ webroot }}"
  args:
    creates: "{{ webroot }}/wp-load.php"
  become_user: "{{ run_as_user }}"

- name: Create wp-config.php
  shell: |
    wp config create --dbname={{ cms_db_name }} --dbuser={{ db_user }} --dbpass={{ lookup('passwordstore', client + '/' + hostname + '/' + bare_url + '/mysql') }} {% if cms_table_prefix|default('blank', True) != 'blank' %}--dbprefix={{ cms_table_prefix}}{% endif %} --path={{ webroot }} --extra-php <<PHP
    define( 'WP_SITEURL', '{{ primary_url }}' );
  args:
    creates: "{{ webroot }}/wp-config.php"
  become_user: "{{ run_as_user }}"

- name: Run the WP installer
  command: "wp core install --url={{ bare_url }} --title='{{ site_title }}' --admin_user=admin --admin_email={{ admin_email }} --admin_password={{ lookup('passwordstore', client + '/' + hostname + '/' + bare_url + '/admin create=true length=32') }}  --path={{ webroot }}"
  changed_when: wpinstaller.stdout != "WordPress is already installed."
  register: wpinstaller
  become_user: "{{ run_as_user }}"
  notify:
    - restart apache
    - restart php-fpm

- name: Install the wp-login companion plugin
  command: "wp login install --activate --path={{ webroot }}"
  args:
    creates: "{{ webroot }}/wp-content/plugins/wp-cli-login-server"
  become_user: "{{ run_as_user }}"

- name: Download the latest Civi archive
  get_url:
    url: https://download.civicrm.org/latest/civicrm-STABLE-wordpress.zip
    dest: /tmp/civicrm-STABLE-wordpress.zip
  when: civicrm == 'Yes'

- name: Unarchive the tarball
  unarchive:
    src: /tmp/civicrm-STABLE-wordpress.zip
    dest: "{{ webroot }}/wp-content/plugins"
    remote_src: yes
    creates: "{{ civiroot }}/composer.json"
  when: civicrm == 'Yes'
  become_user: "{{ run_as_user }}"

- name: Enable CiviCRM
  command: "wp plugin activate civicrm --path={{ webroot }}"
  when: civicrm == 'Yes'
  become_user: "{{ run_as_user }}"