# Necessary because the parent directory isn't "web" so ownership is not the run_as_user
- name: Allow access to git repo for run_as_user
  command: "git config --global --add safe.directory {{ gitroot }}"
  become_user: "{{ run_as_user }}"


- name: Check if 'main' branch exists
  command: git for-each-ref refs/heads/main --format="%(refname)"
  args:
    chdir: "{{ gitroot }}"
  register: main_branch_check
  become_user: "{{ run_as_user }}"
  changed_when: false
  failed_when: false 

- name: Clone standalone from Github
  git:
    repo: https://github.com/civicrm/civicrm-standalone.git
    dest: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"
  when: main_branch_check.stdout | trim == ""

- name: Change branch name to "main"
  command: git branch -m master main
  args:
    chdir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"
  when: main_branch_check.stdout | trim == ""

- name: Set the remote to the actual git repo
  command: git remote set-url origin {{ git_repo_url }}
  args:
    chdir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

- name: Create the web folder
  file:
    path: "{{ webroot }}"
    state: directory
    owner: "{{ run_as_user }}"
    group: "{{ run_as_user }}"
    mode: '0770'

- name: Move the existing public/, index.php, .htaccess and the ext/ files and directories under the webroot.
  command: "git mv {{ item }} {{ webroot }}/"
  args:
    chdir: "{{ gitroot }}"
    creates: "{{ webroot }}/{{ item }}"
  with_items:
    - public
    - index.php
    - .htaccess
    - ext
  become_user: "{{ run_as_user }}"

- name: Set the appRootPath to reflect the nested structure of the standalone codebase.
  lineinfile:
    path: "{{ webroot }}/index.php"
    search_string: '$appRootPath ='
    line: "$appRootPath = implode(DIRECTORY_SEPARATOR, [__DIR__, '..']);"

- name: Update the asset paths in composer.json
  lineinfile:
    path: "{{ gitroot }}/composer.json"
    search_string: '"path": "public/assets"'
    replace: '"path": "web/public/assets"'
    
- name: Get the latest CiviCRM version number
  local_action:
    module: uri
    url: https://latest.civicrm.org/stable.php
    return_content: yes
  run_once: true
  register: civi_ver
  become: no

- name: Update the CiviCRM version in composer.json
  composer:
    command: require
    working_dir: "{{ gitroot }}"
    arguments: "civicrm/civicrm-core:'{{ civi_ver.content }}' civicrm/civicrm-packages:'{{ civi_ver.content }}'"
  become_user: "{{ run_as_user }}"

- name: git add
  command: git add -A
  args:
    chdir: "{{ gitroot }}"
  register: add_result
  changed_when: add_result.stdout != ''
  become_user: "{{ run_as_user }}"

- name: git commit
  command: git commit -m "Nested webroot structure for standalone"
  args:
    chdir: "{{ gitroot }}"
  register: commit_result
  changed_when: commit_result.rc == 0 or 'nothing to commit, working tree clean' in commit_result.stdout
  failed_when: 'commit_result.rc != 0 and not "nothing to commit, working tree clean" in commit_result.stdout_lines'
  become_user: "{{ run_as_user }}"

- name: Composer install (standalone - takes at least 3 minutes)
  composer:
    command: install
    working_dir: "{{ gitroot }}"
    composer_executable: "{{ ansible_env.HOME + '/bin/composer' if 'mayfirst_ng_site' in group_names else '/usr/local/bin/composer' }}"
    executable: "{{ php_path|default(omit) }}"
  become_user: "{{ run_as_user }}"
