- name: Download Drupal 7
  command: "drush dl drupal-7 -y --destination={{ webroot }}/.. --drupal-project-rename=htdocs"
  args:
    creates: "{{ webroot }}/authorize.php"
  become_user: "{{ run_as_user }}"

- name: Install Drupal with drush.
  command: >
    drush site-install standard -y
    --root={{ webroot}}
    --site-name="{{ site_title }}"
    --account-name=admin
    --account-pass={{ lookup('passwordstore', client + '/' + ansible_ssh_host + '/' + bare_url + '/admin create=true length=32') }}
    --db-url=mysql://{{ db_user }}:{{ lookup('passwordstore', client + '/' + ansible_ssh_host + '/' + bare_url + '/mysql create=true length=32') }}@localhost/{{ cms_db_name }}
  args:
    chdir: "{{ webroot }}"
    creates: "{{ webroot }}/sites/default/settings.php"
  become_user: "{{ run_as_user }}"
  notify:
    - restart apache
    - restart php-fpm

- name: Set the D7 .gitignore
  copy:
    src: files/d7-gitignore
    dest: "{{ webroot }}/.gitignore"
  become_user: "{{ run_as_user }}"

- name: Check if Civi is already set up.
  stat: "path={{ civiroot }}/Civi.php"
  register: civi_installed
  ignore_errors: true
  become_user: "{{ run_as_user }}"

- name: Download the latest Civi tarball
  get_url:
    url: https://download.civicrm.org/latest/civicrm-STABLE-drupal.tar.gz
    dest: /tmp/civicrm-STABLE-drupal.tar.gz
  when: civi_installed.stat.exists == false and civicrm == 'Yes'
  become_user: "{{ run_as_user }}"

- name: Unarchive the tarball
  unarchive:
    src: /tmp/civicrm-STABLE-drupal.tar.gz
    dest: "{{ webroot }}/sites/all/modules"
    remote_src: yes
    creates: "{{ civiroot }}/composer.json"
  when: civi_installed.stat.exists == false and civicrm == 'Yes'
  become_user: "{{ run_as_user }}"
