- name: composer create-project
  composer:
    command: create-project
    arguments: drupal/recommended-project "{{ gitroot }}"
    working_dir: "{{ gitroot }}/.."
  become_user: "{{ run_as_user }}"

- name: escape this JSON
  set_fact:
    file_mapping: "{{ {'[web-root]/.htaccess': false, '[web-root]/robots.txt': false} | to_json }}"

- name: Don't touch .htaccess or robots.txt
  composer:
    command: config
    arguments: "--json extra.drupal-scaffold.file-mapping '{{ file_mapping }}'"
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

- name: drush
  composer:
    command: require
    arguments: drush/drush
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

- name: Install Drupal with drush.
  command: >
    {{ gitroot }}/vendor/bin/drush site-install standard -y
    --root={{ webroot}}
    --site-name="{{ site_title }}"
    --sites-subdir=default
    --account-name=admin
    --account-pass={{ lookup('passwordstore', client + '/' + hostname + '/' + bare_url + '/admin create=true length=32') }}
    --db-url=mysql://{{ db_user }}:{{ lookup('passwordstore', client + '/' + hostname + '/' + bare_url + '/mysql create=true length=32') }}@localhost/{{ cms_db_name }}
  args:
    chdir: "{{ webroot }}"
    creates: "{{ webroot }}/sites/default/settings.php"
  become_user: "{{ run_as_user }}"
  notify:
    - restart apache
    - restart php-fpm

- name: Push the settings.php template
  template:
    src: "templates/{{ cms }}-settings.j2"
    dest: "{{ webroot }}/sites/default/settings.php"
    owner: "{{ run_as_user }}"
    group: "{{ run_as_user }}"
    mode: 0660
  become_user: root

- name: Enable composer patching
  composer:
    command: config
    arguments: --no-plugins allow-plugins.cweagans/composer-patches true
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

- name: Enable Civi asset plugin
  composer:
    command: config
    arguments: --no-plugins allow-plugins.civicrm/civicrm-asset-plugin true
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

- name: Enable Civi downloads plugin
  composer:
    command: config
    arguments: --no-plugins allow-plugins.civicrm/composer-downloads-plugin true
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

- name: Enable Civi compile plugin
  composer:
    command: config
    arguments: --no-plugins allow-plugins.civicrm/composer-compile-plugin true
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

- name: Whitelist Civi compile plugins
  composer:
    command: config
    arguments: --json extra.compile-whitelist  '[ "civicrm/composer-compile-lib", "civicrm/civicrm-core" ]'
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"

# That psr/simple-cache shouldn't be necessary forever I hope - but you need it for D11 at present.
- name: Install CiviCRM
  composer:
    command: require
    arguments: civicrm/civicrm-core civicrm/civicrm-packages civicrm/civicrm-drupal-8 psr/simple-cache:~1.0.1
    working_dir: "{{ gitroot }}"
  become_user: "{{ run_as_user }}"
  when: civicrm == 'Yes'
