- name: Set a drushrc.php
  template:
    src: templates/drushrc.j2
    dest: "{{ item.item.value.webroot }}/sites/default/drushrc.php"
    owner: "{{ item.item.value.run_as_user }}"
    group: "{{ item.item.value.run_as_user }}"
  when: item.item.value.cms == 'Drupal'
  become_user: root

- name: Enable Megaphone monitoring
  command: "cv en com.megaphonetech.monitoring"
  args:
    chdir: "{{ item.item.value.webroot }}"
  become_user: "{{ item.item.value.run_as_user }}"

- name: Create a role for monitoring
  command: "drush --root={{ item.item.value.webroot }} role-create 'monitor'"
  register: create_monitoring_role
  become_user: "{{ item.item.value.run_as_user }}"
  changed_when: create_monitoring_role.rc == 0
  failed_when: not(create_monitoring_role.rc == 0 or create_monitoring_role.stderr is search("Duplicate entry"))

  # drush 7 has a bug and can't handle this.
- name: Add remote monitoring permission to monitor role
  command: "drush8 --root={{ item.item.value.webroot }} role-add-perm 'monitor' 'remote monitoring'"
  become_user: "{{ item.item.value.run_as_user }}"

  # We don't actually record the password because we don't care what it is.
- name: Create a user for monitoring
  command: "drush --root={{ item.item.value.webroot }} user-create {{ monitoring_user }} --mail='{{ monitoring_email }}' --password='{{ lookup('password', '/dev/null length=32') }}'"
  register: create_monitoring_user
  become_user: "{{ item.item.value.run_as_user }}"
  changed_when: create_monitoring_user.rc == 0
  failed_when: not(create_monitoring_user.rc == 0 or create_monitoring_user.stderr is search("There is already a user account with the email"))
  
- name: Add the monitoring role to the monitoring user
  command: "drush --root={{ item.item.value.webroot }} user-add-role 'monitor' {{ monitoring_user }}"
  register: create_monitoring_user
  become_user: "{{ item.item.value.run_as_user }}"
  changed_when: create_monitoring_user.rc == 0
  failed_when: not(create_monitoring_user.rc == 0 or create_monitoring_user.stderr is search("There is already a user account with the email"))

- name: Expand the number of log messages to keep
  command: "drush --root={{ item.item.value.webroot }} vset dblog_row_limit 1000000"
  become_user: "{{ item.item.value.run_as_user }}"

- name: Don't print errors to screen
  command: "drush --root={{ item.item.value.webroot }} vset error_level 0"
  become_user: "{{ item.item.value.run_as_user }}"

- name: Enable role_watchdog
  command: "drush --root={{ item.item.value.webroot }} en -y role_watchdog"
  args:
    creates: "{{ item.item.value.webroot }}/sites/all/modules/role_watchdog"
  become_user: "{{ item.item.value.run_as_user }}"

- name: Enable clear_password_field
  command: "drush --root={{ item.item.value.webroot }} en -y clear_password_field"
  args:
    creates: "{{ item.item.value.webroot }}/sites/all/modules/clear_password_field"
  become_user: "{{ item.item.value.run_as_user }}"

- name: Enable hide_php_fatal_error 
  command: "drush --root={{ item.item.value.webroot }} en -y hide_php_fatal_error"
  args:
    creates: "{{ item.item.value.webroot }}/sites/all/modules/hide_php_fatal_error"
  become_user: "{{ item.item.value.run_as_user }}"

- name: Enable remove_generator 
  command: "drush --root={{ item.item.value.webroot }} en -y remove_generator"
  args:
    creates: "{{ item.item.value.webroot }}/sites/all/modules/remove_generator"
  become_user: "{{ item.item.value.run_as_user }}"
