- name: Set a drushrc.php
  template:
    src: templates/drushrc.j2
    dest: "{{ item.item.value.webroot }}/sites/default/drushrc.php"
    owner: "{{ item.item.value.run_as_user }}"
    group: "{{ item.item.value.run_as_user }}"
  when: item.item.value.cms == 'Drupal'
  become_user: root

  # We don't actually record the password because we don't care what it is.
- name: Create a user for monitoring
  command: "drush --root={{ item.item.value.webroot }} user-create {{ monitoring_user }} --mail='{{ monitoring_email }}' --password='{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}'"
  register: create_monitoring_user
  become_user: "{{ item.item.value.run_as_user }}"
  changed_when: create_monitoring_user.rc == 0
  failed_when: not(create_monitoring_user.rc == 0 or create_monitoring_user.stderr is search("There is already a user account with the email"))
